export const ADD_NEW_ROBOT_REQUEST = 'ADD_NEW_ROBOT_REQUEST'
export const ADD_NEW_ROBOT_SUCCESS = 'ADD_NEW_ROBOT_SUCCESS'
export const ADD_NEW_ROBOT_ERROR = 'ADD_NEW_ROBOT_ERROR'


export const SET_ROBOT_ACTIVE_REQUEST = 'SET_ROBOT_ACTIVE_REQUEST'
export const SET_ROBOT_ACTIVE_SUCCESS = 'SET_ROBOT_ACTIVE_SUCCESS'
export const SET_ROBOT_ACTIVE_ERROR = 'SET_ROBOT_ACTIVE_ERROR'


export const SET_ROBOT_ACTIVITY_REQUEST = 'SET_ROBOT_ACTIVITY_REQUEST'
export const SET_ROBOT_ACTIVITY_SUCCESS = 'SET_ROBOT_ACTIVITY_SUCCESS'
export const SET_ROBOT_ACTIVITY_ERROR = 'SET_ROBOT_ACTIVITY_ERROR'


export const MINE_FOO_REQUEST = 'MINE_FOO_REQUEST'
export const MINE_FOO_SUCCESS = 'MINE_FOO_SUCCESS'
export const MINE_FOO_ERROR = 'MINE_FOO_ERROR'

export const CLEAN_ROBOT = 'CLEAN_ROBOT'


export const CHANGE_ACTIVITY_DURATION = 5000
export const MINE_FOO_DURATION = 1000
export const INIT_MINE_BAR_DURATION = 1000
export const ASSEMBLE_FOOBAR_DURATION = 2000

export const MINE_FOO_NAME = 'mineFoo'
export const MINE_BAR_NAME = 'mineBar'
export const ASSEMBLE_FOOBAR_NAME = 'assembleFoobar'

export const MINE_FOO = {
  name: MINE_FOO_NAME,
  duration: MINE_FOO_DURATION
}

export const MINE_BAR = {
  name: MINE_BAR_NAME,
  duration: INIT_MINE_BAR_DURATION
}
export const ASSEMBLE_FOOBAR = {
  name: ASSEMBLE_FOOBAR_NAME,
  duration: ASSEMBLE_FOOBAR_DURATION
}
