export const MINE_FOO_REQUEST = 'MINE_FOO_REQUEST'
export const MINE_FOO_SUCCESS = 'MINE_FOO_SUCCESS'
export const MINE_FOO_ERROR = 'MINE_FOO_ERROR'

export const MINE_BAR_REQUEST = 'MINE_BAR_REQUEST'
export const MINE_BAR_SUCCESS = 'MINE_BAR_SUCCESS'
export const MINE_BAR_ERROR = 'MINE_BAR_ERROR'

export const ASSEMBLE_FOOBAR_REQUEST = 'ASSEMBLE_FOOBAR_REQUEST'
export const ASSEMBLE_FOOBAR_SUCCESS = 'ASSEMBLE_FOOBAR_SUCCESS'
export const ASSEMBLE_FOOBAR_ERROR = 'ASSEMBLE_FOOBAR_ERROR'

export const ROBOT_BOUGHT_REQUEST = 'ROBOT_BOUGHT_REQUEST'
export const ROBOT_BOUGHT_SUCCESS = 'ROBOT_BOUGHT_SUCCESS'
export const ROBOT_BOUGHT_ERROR = 'ROBOT_BOUGHT_ERROR'

export const CLEAN_GAME = 'CLEAN_GAME'

export const NB_ROBOTS_WIN_CONDITION = 20
